//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TASK
    {
        public int TASK_ID { get; set; }
        public string TASK_NAME { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual TBL_DEVELOPER TBL_DEVELOPER { get; set; }
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
