//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEVELOPER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEVELOPER()
        {
            this.TBL_TASK = new HashSet<TBL_TASK>();
        }
    
        public int DEV_ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<int> DEV_LVL { get; set; }
        public string DEV_TASK { get; set; }
    
        public virtual TBL_ROL TBL_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TASK> TBL_TASK { get; set; }
    }
}
